// -------------------------------------------------
// AUTO-GENERATED by ScriptTemplateDiscovery.
// Do not edit manually. Regenerate via:
//   Tools > Script Templates > Regenerate Menu Items
// Or by adding/removing .txt files in the
// ScriptTemplates folder.
// -------------------------------------------------

using UnityEditor;

namespace Nenoso.ScriptTemplates.Editor
{
    internal static class GeneratedMenuItems
    {

        [MenuItem("Assets/Create/C#/Abstract Class", false, -220)]
        private static void Create_Abstract_Class()
        {
            ScriptTemplateMenuItems.CreateFromTemplate("AbstractClass.txt", "NewAbstractClass.cs");
        }

        [MenuItem("Assets/Create/C#/Class (Plain)", false, -219)]
        private static void Create_Class_Plain()
        {
            ScriptTemplateMenuItems.CreateFromTemplate("Class.txt", "NewClass.cs");
        }

        [MenuItem("Assets/Create/C#/Enum", false, -218)]
        private static void Create_Enum()
        {
            ScriptTemplateMenuItems.CreateFromTemplate("Enum.txt", "NewEnum.cs");
        }

        [MenuItem("Assets/Create/C#/Interface", false, -217)]
        private static void Create_Interface()
        {
            ScriptTemplateMenuItems.CreateFromTemplate("Interface.txt", "INewInterface.cs");
        }

        [MenuItem("Assets/Create/C#/ScriptableObject", false, -216)]
        private static void Create_ScriptableObject()
        {
            ScriptTemplateMenuItems.CreateFromTemplate("ScriptableObject.txt", "NewScriptableObject.cs");
        }

        [MenuItem("Assets/Create/C#/Static Class", false, -215)]
        private static void Create_Static_Class()
        {
            ScriptTemplateMenuItems.CreateFromTemplate("StaticClass.txt", "NewStaticClass.cs");
        }

        [MenuItem("Assets/Create/C#/Struct", false, -214)]
        private static void Create_Struct()
        {
            ScriptTemplateMenuItems.CreateFromTemplate("Struct.txt", "NewStruct.cs");
        }
    }
}
